# -*- coding: utf-8 -*-
"""lab exam1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbS8PA3O749JSKua-hVAQ-tLMvqM88jv
"""

import pandas as pd

data = {'product_Name': ['ac', 'shirt', 'table', 'tava'],
        'category': ['electronics', 'clothing', 'home', 'kitchen'],
        'price': [50000, 2000, 10000, 800],
        'quantity_sold': [3, 8, 6, 10]}

df = pd.DataFrame(data)

pivot_table = pd.pivot_table(df, values=['quantity_sold', 'price'], aggfunc=['sum', 'mean'], index='category')
print(pivot_table)

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/content/mtcars (1).csv')

plt.figure(figsize=(8, 6))
plt.hist(df['mpg'], bins=10, color='skyblue', edgecolor='black')
plt.title('Histogram of MPG (Miles per Gallon)')
plt.xlabel('MPG')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(df['wt'], df['mpg'], color='green', marker='o')
plt.title('Scatter Plot of Weight vs. MPG')
plt.xlabel('Weight')
plt.ylabel('MPG')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

transmission_counts = df['am'].value_counts()
plt.figure(figsize=(8, 6))
transmission_counts.plot(kind='bar', color='orange')
plt.title('Frequency Distribution of Transmission Type')
plt.xlabel('Transmission Type (0 = Automatic, 1 = Manual)')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars (1).csv')
plt.boxplot(df['mpg'])
plt.title('boxplot')
plt.xlabel('height')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 6))
plt.boxplot(df['mpg'], vert=False)
plt.title('Box and Whisker Plot of MPG')
plt.xlabel('MPG')
plt.grid(axis='x', alpha=0.7)
plt.show()